#SingleInstance force
#Hotstring EndChars `t`n
SetKeyDelay, 0

#ifWinActive, ahk_class PuTTY
{
+up::SendInput           {ESC}[1;2A
+down::SendInput         {ESC}[1;2B
+right::SendInput        {ESC}[1;2C
+left::SendInput         {ESC}[1;2D
+end::SendInput          {ESC}[1;2F
+home::SendInput         {ESC}[1;2H
!up::SendInput           {ESC}[1;3A
!down::SendInput         {ESC}[1;3B
!right::SendInput        {ESC}[1;3C
!left::SendInput         {ESC}[1;3D
!end::SendInput          {ESC}[1;3F
!home::SendInput         {ESC}[1;3H
!+up::SendInput          {ESC}[1;4A
!+down::SendInput        {ESC}[1;4B
!+right::SendInput       {ESC}[1;4C
!+left::SendInput        {ESC}[1;4D
!+end::SendInput         {ESC}[1;4F
!+home::SendInput        {ESC}[1;4H
^up::SendInput           {ESC}[1;5A
^down::SendInput         {ESC}[1;5B
^right::SendInput        {ESC}[1;5C
^left::SendInput         {ESC}[1;5D
^end::SendInput          {ESC}[1;5F
^home::SendInput         {ESC}[1;5H
^+up::SendInput          {ESC}[1;6A
^+down::SendInput        {ESC}[1;6B
^+right::SendInput       {ESC}[1;6C
^+left::SendInput        {ESC}[1;6D
^+end::SendInput         {ESC}[1;6F
^+home::SendInput        {ESC}[1;6H
!^up::SendInput          {ESC}[1;7A
!^down::SendInput        {ESC}[1;7B
!^right::SendInput       {ESC}[1;7C
!^left::SendInput        {ESC}[1;7D
!^end::SendInput         {ESC}[1;7F
!^home::SendInput        {ESC}[1;7H
+!^up::SendInput         {ESC}[1;8A
+!^down::SendInput       {ESC}[1;8B
+!^right::SendInput      {ESC}[1;8C
+!^left::SendInput       {ESC}[1;8D
+!^end::SendInput        {ESC}[1;8F
+!^home::SendInput       {ESC}[1;8H
+f1::SendInput           {ESC}O2P
+f2::SendInput           {ESC}O2Q
+f3::SendInput           {ESC}O2R
+f4::SendInput           {ESC}O2S
+f5::SendInput           {ESC}[15;2~
+f6::SendInput           {ESC}[17;2~
+f7::SendInput           {ESC}[18;2~
+f8::SendInput           {ESC}[19;2~
+f9::SendInput           {ESC}[20;2~
+f10::SendInput          {ESC}[21;2~
+f11::SendInput          {ESC}[23;2~
+f12::SendInput          {ESC}[24;2~
^f1::SendInput           {ESC}O5P
^f2::SendInput           {ESC}O5Q
^f3::SendInput           {ESC}O5R
^f4::SendInput           {ESC}O5S
^f5::SendInput           {ESC}[15;5~
^f6::SendInput           {ESC}[17;5~
^f7::SendInput           {ESC}[18;5~
^f8::SendInput           {ESC}[19;5~
^f9::SendInput           {ESC}[20;5~
^f10::SendInput          {ESC}[21;5~
^f11::SendInput          {ESC}[23;5~
^f12::SendInput          {ESC}[24;5~
+^f1::SendInput          {ESC}O6P
+^f2::SendInput          {ESC}O6Q
+^f3::SendInput          {ESC}O6R
+^f4::SendInput          {ESC}O6S
+^f5::SendInput          {ESC}[15;6~
+^f6::SendInput          {ESC}[17;6~
+^f7::SendInput          {ESC}[18;6~
+^f8::SendInput          {ESC}[19;6~
+^f9::SendInput          {ESC}[20;6~
+^f10::SendInput         {ESC}[21;6~
+^f11::SendInput         {ESC}[23;6~
+^f12::SendInput         {ESC}[24;6~
!f1::SendInput           {ESC}O3P
!f2::SendInput           {ESC}O3Q
!f3::SendInput           {ESC}O3R
!f4::SendInput           {ESC}O3S
!f5::SendInput           {ESC}[15;3~
!f6::SendInput           {ESC}[17;3~
!f7::SendInput           {ESC}[18;3~
!f8::SendInput           {ESC}[19;3~
!f9::SendInput           {ESC}[20;3~
!f10::SendInput          {ESC}[21;3~
!f11::SendInput          {ESC}[23;3~
!f12::SendInput          {ESC}[24;3~
+!f1::SendInput          {ESC}O4P
+!f2::SendInput          {ESC}O4Q
+!f3::SendInput          {ESC}O4R
+!f4::SendInput          {ESC}O4S
+!f5::SendInput          {ESC}[15;4~
+!f6::SendInput          {ESC}[17;4~
+!f7::SendInput          {ESC}[18;4~
+!f8::SendInput          {ESC}[19;4~
+!f9::SendInput          {ESC}[20;4~
+!f10::SendInput         {ESC}[21;4~
+!f11::SendInput         {ESC}[23;4~
+!f12::SendInput         {ESC}[24;4~
!^f1::SendInput          {ESC}O7P
!^f2::SendInput          {ESC}O7Q
!^f3::SendInput          {ESC}O7R
!^f4::SendInput          {ESC}O7S
!^f5::SendInput          {ESC}[15;7~
!^f6::SendInput          {ESC}[17;7~
!^f7::SendInput          {ESC}[18;7~
!^f8::SendInput          {ESC}[19;7~
!^f9::SendInput          {ESC}[20;7~
!^f10::SendInput         {ESC}[21;7~
!^f11::SendInput         {ESC}[23;7~
!^f12::SendInput         {ESC}[24;7~
+!^f1::SendInput         {ESC}O8P
+!^f2::SendInput         {ESC}O8Q
+!^f3::SendInput         {ESC}O8R
+!^f4::SendInput         {ESC}O8S
+!^f5::SendInput         {ESC}[15;8~
+!^f6::SendInput         {ESC}[17;8~
+!^f7::SendInput         {ESC}[18;8~
+!^f8::SendInput         {ESC}[19;8~
+!^f9::SendInput         {ESC}[20;8~
+!^f10::SendInput        {ESC}[21;8~
+!^f11::SendInput        {ESC}[23;8~
+!^f12::SendInput        {ESC}[24;8~
+insert::SendInput       {ESC}[2;2~
!insert::SendInput       {ESC}[2;3~
!+insert::SendInput      {ESC}[2;4~
^insert::SendInput       {ESC}[2;5~
^+insert::SendInput      {ESC}[2;6~
!^insert::SendInput      {ESC}[2;7~
!^+insert::SendInput     {ESC}[2;8~
+delete::SendInput       {ESC}[3;2~
!delete::SendInput       {ESC}[3;3~
!+delete::SendInput      {ESC}[3;4~
^delete::SendInput       {ESC}[3;5~
^+delete::SendInput      {ESC}[3;6~
!^delete::SendInput      {ESC}[3;7~
!^+delete::SendInput     {ESC}[3;8~
+tab::SendInput          {ESC}[z2a
!tab::SendInput          {ESC}[z3a
!+tab::SendInput         {ESC}[z4a
^tab::SendInput          {ESC}[z5a
+^tab::SendInput         {ESC}[z6a
!^tab::SendInput         {ESC}[z7a
!^+tab::SendInput        {ESC}[z8a
+return::SendInput       {ESC}[z2b
!return::SendInput       {ESC}[z3b
!+return::SendInput      {ESC}[z4b
^return::SendInput       {ESC}[z5b
^+return::SendInput      {ESC}[z6b
!^return::SendInput      {ESC}[z7b
!^+return::SendInput     {ESC}[z8b
+backspace::SendInput    {ESC}[z2c
!backspace::SendInput    {ESC}[z3c
!+backspace::SendInput   {ESC}[z4c
^backspace::SendInput    {ESC}[z5c
^+backspace::SendInput   {ESC}[z6c
!^backspace::SendInput   {ESC}[z7c
!^+backspace::SendInput  {ESC}[z8c
+pause::SendInput        {ESC}[z2d
!pause::SendInput        {ESC}[z3d
!+pause::SendInput       {ESC}[z4d
^pause::SendInput        {ESC}[z5d
^+pause::SendInput       {ESC}[z6d
!^pause::SendInput       {ESC}[z7d
+!^pause::SendInput      {ESC}[z8d
end::SendInput           {ESC}[F
home::SendInput          {ESC}[H
^;::SendInput            {ESC}[e;
^'::SendInput            {ESC}[e'
^,::SendInput            {ESC}[e,
^.::SendInput            {ESC}[e.
}

::jbos::jobs
::pw::chl1987.lxm1990
